#############################################################
# runs VIC Fortran routing code
# note: there are two uh_s files. one from the basin delineation
# and a second generated by this code. the first points to the second
# if the second doesn't exist, a .none file is specified, and the 
# second is generated. confusing I know.  
#############################################################

## user inputs
setwd('/work/dbroman/projects/skokomish/run_vic/')
route_list = scan('lib/route_list.txt', what = 'character')
control_file = readLines('lib/routectrl.inp')
data_name = 'skokomish'

output_dir = paste0('data/routed/livneh_historic/')
if(dir.exists(output_dir) == F){
	dir.create(output_dir)
}
nroute = length(route_list)
for(iroute in 1:nroute){
	route_sel = route_list[iroute]
	uh_file = paste0(route_sel, '.uh_s')
	log_file = paste0('logs/log-route-livneh_historic-', route_sel, '.txt')
	control_file[3] = paste0('data/processed/route/', route_sel,'.fdir')
	control_file[15] = paste0('data/processed/route/', route_sel,'.frac')
	if(file.exists(uh_file) == FALSE){
		control_file[17] = paste0('data/processed/route/', route_sel,'.none')
	} else {
		control_file[17] = paste0('data/processed/route/', route_sel,'.uh_s')
	}
	control_file[19] = paste0('data/output/livneh_historic/hydro_')
	control_file[22] = paste0(output_dir)
	control_file[24] = '1950 01 2013 12'
	control_file[25] = '1950 01 2013 12'
	write(control_file, paste0('lib/routectrl.livneh_historic.', route_sel, '.', data_name, '.inp'))
	runcmd = paste0('./src/rout_f77/rout lib/routectrl.livneh_historic.', route_sel, '.', data_name, '.inp')
	 # ' > ',  log_file,' 2>&1 &')
	system(runcmd)	
}

system(paste0('mv *.uh_s data/processed/route/uh_s/'))
